branch-defaults:
  default:
    environment: Uda-env
deploy:
  artifact: www/Archive.zip
environment-defaults:
  Uda-env:
    branch: null
    repository: null
global:
  application_name: uda
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
